version: '3.4'

services:

  latigo-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    environment:
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - GORDO_PROJECT=${GORDO_PROJECT}


  latigo-executor-1:
    build:
      context: .
      dockerfile: Dockerfile.executor
    environment:
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - GORDO_PROJECT=${GORDO_PROJECT}

  latigo-executor-2:
    build:
      context: .
      dockerfile: Dockerfile.executor
    environment:
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - GORDO_PROJECT=${GORDO_PROJECT}


