version: '3.4'

services:

# Scheduler that produces tasks for executors
  latigo-scheduler:
    image: latigo-base
    restart: always
    container_name: latigo-scheduler
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    volumes:
      - ../volumes/latigo/scheduler:/tmp/data:Z
    environment:
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - LATIGO_SCHEDULER_CONFIG_FILE=${LATIGO_SCHEDULER_CONFIG_FILE}
      - LATIGO_SCHEDULER_PREDICTION_START_TIME=${LATIGO_SCHEDULER_PREDICTION_START_TIME}
      - LATIGO_SCHEDULER_PREDICTION_INTERVAL=${LATIGO_SCHEDULER_PREDICTION_INTERVAL}
      - LATIGO_SCHEDULER_PREDICTION_DELAY=${LATIGO_SCHEDULER_PREDICTION_DELAY}
      - LATIGO_SCHEDULER_PROJECTS=${LATIGO_SCHEDULER_PROJECTS}
      - LATIGO_GORDO_CONNECTION_STRING=${LATIGO_GORDO_CONNECTION_STRING}
      - LATIGO_GORDO_RESOURCE=${LATIGO_GORDO_RESOURCE}
      - LATIGO_GORDO_TENANT=${LATIGO_GORDO_TENANT}
      - LATIGO_GORDO_AUTH_HOST_URL=${LATIGO_GORDO_AUTH_HOST_URL}
      - LATIGO_GORDO_CLIENT_ID=${LATIGO_GORDO_CLIENT_ID}
      - LATIGO_GORDO_CLIENT_SECRET=${LATIGO_GORDO_CLIENT_SECRET}
      - LATIGO_ENABLE_AUTH_VERIFICATION=${LATIGO_ENABLE_AUTH_VERIFICATION:-True}
    command: ["/app/bin/scheduler.py"]

# First executor for executing tasks from scheduler
  latigo-executor-1:
    image: latigo-base
    restart: always
    container_name: latigo-executor-1
    build:
      context: .
      dockerfile: Dockerfile.executor
    environment:
      - LATIGO_EXECUTOR_INSTANCE_COUNT=${LATIGO_EXECUTOR_INSTANCE_COUNT}
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - LATIGO_EXECUTOR_CONFIG_FILE=${LATIGO_EXECUTOR_CONFIG_FILE}
      - LATIGO_GORDO_CONNECTION_STRING=${LATIGO_GORDO_CONNECTION_STRING}
      - LATIGO_GORDO_RESOURCE=${LATIGO_GORDO_RESOURCE}
      - LATIGO_GORDO_TENANT=${LATIGO_GORDO_TENANT}
      - LATIGO_GORDO_AUTH_HOST_URL=${LATIGO_GORDO_AUTH_HOST_URL}
      - LATIGO_GORDO_CLIENT_ID=${LATIGO_GORDO_CLIENT_ID}
      - LATIGO_GORDO_CLIENT_SECRET=${LATIGO_GORDO_CLIENT_SECRET}
      - LATIGO_TIME_SERIES_RESOURCE=${LATIGO_TIME_SERIES_RESOURCE}
      - LATIGO_TIME_SERIES_TENANT=${LATIGO_TIME_SERIES_TENANT}
      - LATIGO_TIME_SERIES_BASE_URL=${LATIGO_TIME_SERIES_BASE_URL}
      - LATIGO_TIME_SERIES_AUTH_HOST_URL=${LATIGO_TIME_SERIES_AUTH_HOST_URL}
      - LATIGO_TIME_SERIES_CLIENT_ID=${LATIGO_TIME_SERIES_CLIENT_ID}
      - LATIGO_TIME_SERIES_CLIENT_SECRET=${LATIGO_TIME_SERIES_CLIENT_SECRET}
      - LATIGO_ENABLE_AUTH_VERIFICATION=${LATIGO_ENABLE_AUTH_VERIFICATION:-True}
    command: ["/app/bin/executor.py"]

# Second executor for executing tasks from scheduler
  latigo-executor-2:
    image: latigo-base
    restart: always
    container_name: latigo-executor-2
    build:
      context: .
      dockerfile: Dockerfile.executor
    environment:
      - LATIGO_EXECUTOR_INSTANCE_COUNT=${LATIGO_EXECUTOR_INSTANCE_COUNT}
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - LATIGO_EXECUTOR_CONFIG_FILE=${LATIGO_EXECUTOR_CONFIG_FILE}
      - LATIGO_GORDO_CONNECTION_STRING=${LATIGO_GORDO_CONNECTION_STRING}
      - LATIGO_GORDO_RESOURCE=${LATIGO_GORDO_RESOURCE}
      - LATIGO_GORDO_TENANT=${LATIGO_GORDO_TENANT}
      - LATIGO_GORDO_AUTH_HOST_URL=${LATIGO_GORDO_AUTH_HOST_URL}
      - LATIGO_GORDO_CLIENT_ID=${LATIGO_GORDO_CLIENT_ID}
      - LATIGO_GORDO_CLIENT_SECRET=${LATIGO_GORDO_CLIENT_SECRET}
      - LATIGO_TIME_SERIES_RESOURCE=${LATIGO_TIME_SERIES_RESOURCE}
      - LATIGO_TIME_SERIES_TENANT=${LATIGO_TIME_SERIES_TENANT}
      - LATIGO_TIME_SERIES_BASE_URL=${LATIGO_TIME_SERIES_BASE_URL}
      - LATIGO_TIME_SERIES_AUTH_HOST_URL=${LATIGO_TIME_SERIES_AUTH_HOST_URL}
      - LATIGO_TIME_SERIES_CLIENT_ID=${LATIGO_TIME_SERIES_CLIENT_ID}
      - LATIGO_TIME_SERIES_CLIENT_SECRET=${LATIGO_TIME_SERIES_CLIENT_SECRET}
      - LATIGO_ENABLE_AUTH_VERIFICATION=${LATIGO_ENABLE_AUTH_VERIFICATION:-True}
    command: ["/app/bin/executor.py"]
