version: '3.4'

services:

  latigo-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    environment:
      - AAD_APPLICATION_SECRET=${AAD_APPLICATION_SECRET}
      - AAD_TENANT_ID=${AAD_TENANT_ID}
      - AAD_APPLICATION_ID=${AAD_APPLICATION_ID}
      - KUSTO_URI=${KUSTO_URI}
      - KUSTO_INGEST_URI=${KUSTO_INGEST_URI}
      - KUSTO_DATABASE=${KUSTO_DATABASE}
      - SERVICE_BUSS_CONN_STR=${SERVICE_BUSS_CONN_STR}
      - GORDO_PROJECT=${GORDO_PROJECT}


  latigo-executor-1:
    build:
      context: .
      dockerfile: Dockerfile.executor
    environment:
      - AAD_APPLICATION_SECRET=${AAD_APPLICATION_SECRET}
      - AAD_TENANT_ID=${AAD_TENANT_ID}
      - AAD_APPLICATION_ID=${AAD_APPLICATION_ID}
      - KUSTO_URI=${KUSTO_URI}
      - KUSTO_INGEST_URI=${KUSTO_INGEST_URI}
      - KUSTO_DATABASE=${KUSTO_DATABASE}
      - SERVICE_BUSS_CONN_STR=${SERVICE_BUSS_CONN_STR}
      - GORDO_PROJECT=${GORDO_PROJECT}
      - - LATIGO_EXECUTOR_EVENT_HUB=${LATIGO_EXECUTOR_EVENT_HUB}


  latigo-executor-2:
    build:
      context: .
      dockerfile: Dockerfile.executor
    environment:
      - AAD_APPLICATION_SECRET=${AAD_APPLICATION_SECRET}
      - AAD_TENANT_ID=${AAD_TENANT_ID}
      - AAD_APPLICATION_ID=${AAD_APPLICATION_ID}
      - KUSTO_URI=${KUSTO_URI}
      - KUSTO_INGEST_URI=${KUSTO_INGEST_URI}
      - KUSTO_DATABASE=${KUSTO_DATABASE}
      - SERVICE_BUSS_CONN_STR=${SERVICE_BUSS_CONN_STR}
      - GORDO_PROJECT=${GORDO_PROJECT}
      - LATIGO_EXECUTOR_EVENT_HUB=${LATIGO_EXECUTOR_EVENT_HUB}

