version: '3.4'

services:

  latigo-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    environment:
      - GORDO_PROJECT=${GORDO_PROJECT}


  latigo-executor-1:
    build:
      context: .
      dockerfile: Dockerfile.executor
    environment:
      - GORDO_PROJECT=${GORDO_PROJECT}
      - LATIGO_EXECUTOR_EVENT_HUB=${LATIGO_EXECUTOR_EVENT_HUB}


  latigo-executor-2:
    build:
      context: .
      dockerfile: Dockerfile.executor
    environment:
      - GORDO_PROJECT=${GORDO_PROJECT}
      - LATIGO_EXECUTOR_EVENT_HUB=${LATIGO_EXECUTOR_EVENT_HUB}

