version: '3.4'

services:

  latigo-scheduler:
    image: latigo-scheduler
    restart: always
    container_name: latigo-scheduler
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    links:
      - postgres
    environment:
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - LATIGO_INTERNAL_DATABASE=${LATIGO_INTERNAL_DATABASE}
      - LATIGO_SCHEDULER_CONFIG_FILE=${LATIGO_SCHEDULER_CONFIG_FILE}
      - LATIGO_INSTANCE_NAME="latigo-scheduler"

  latigo-executor-1:
    image: latigo-executor
    restart: always
    container_name: latigo-executor-1
    build:
      context: .
      dockerfile: Dockerfile.executor
    links:
      - postgres
    environment:
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - LATIGO_INTERNAL_DATABASE=${LATIGO_INTERNAL_DATABASE}
      - LATIGO_EXECUTOR_CONFIG_FILE=${LATIGO_EXECUTOR_CONFIG_FILE}
      - LATIGO_SENSOR_DATA_CONNECITON=${LATIGO_SENSOR_DATA_CONNECITON}
      - LATIGO_PREDICTION_STORAGE_CONNECITON=${LATIGO_PREDICTION_STORAGE_CONNECITON}
      - LATIGO_INSTANCE_NAME="latigo-executor-1"

  latigo-executor-2:
    image: latigo-executor
    restart: always
    container_name: latigo-executor-2
    build:
      context: .
      dockerfile: Dockerfile.executor
    links:
      - postgres
    environment:
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - LATIGO_INTERNAL_DATABASE=${LATIGO_INTERNAL_DATABASE}
      - LATIGO_EXECUTOR_CONFIG_FILE=${LATIGO_EXECUTOR_CONFIG_FILE}
      - LATIGO_SENSOR_DATA_CONNECITON=${LATIGO_SENSOR_DATA_CONNECITON}
      - LATIGO_PREDICTION_STORAGE_CONNECITON=${LATIGO_PREDICTION_STORAGE_CONNECITON}
      - LATIGO_INSTANCE_NAME="latigo-executor-2"

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
     - ./volumes/postgres:/var/lib/postgresql/data:Z

