version: '3.4'

services:

# Scheduler that produces tasks for executors
  latigo-scheduler:
    image: latigo-scheduler
    restart: always
    container_name: latigo-scheduler
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    volumes:
      - ../volumes/latigo/scheduler:/tmp/data:Z
    environment:
      - LATIGO_INSTANCE_NAME="latigo-scheduler"
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - LATIGO_SCHEDULER_CONFIG_FILE=${LATIGO_SCHEDULER_CONFIG_FILE}
      - LATIGO_GORDO_CONNECTION_STRING=${LATIGO_GORDO_CONNECTION_STRING}
      - LATIGO_GORDO_RESOURCE=${LATIGO_GORDO_RESOURCE}
      - LATIGO_GORDO_TENANT=${LATIGO_GORDO_TENANT}
      - LATIGO_GORDO_AUTH_HOST_URL=${LATIGO_GORDO_AUTH_HOST_URL}
      - LATIGO_GORDO_CLIENT_ID=${LATIGO_GORDO_CLIENT_ID}
      - LATIGO_GORDO_CLIENT_SECRET=${LATIGO_GORDO_CLIENT_SECRET}

# First executor for executing tasks from scheduler
  latigo-executor-1:
    image: latigo-executor
    restart: always
    container_name: latigo-executor-1
    build:
      context: .
      dockerfile: Dockerfile.executor
    environment:
      - LATIGO_INSTANCE_NAME="latigo-executor-1"
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - LATIGO_EXECUTOR_CONFIG_FILE=${LATIGO_EXECUTOR_CONFIG_FILE}
      - LATIGO_GORDO_CONNECTION_STRING=${LATIGO_GORDO_CONNECTION_STRING}
      - LATIGO_GORDO_RESOURCE=${LATIGO_GORDO_RESOURCE}
      - LATIGO_GORDO_TENANT=${LATIGO_GORDO_TENANT}
      - LATIGO_GORDO_AUTH_HOST_URL=${LATIGO_GORDO_AUTH_HOST_URL}
      - LATIGO_GORDO_CLIENT_ID=${LATIGO_GORDO_CLIENT_ID}
      - LATIGO_GORDO_CLIENT_SECRET=${LATIGO_GORDO_CLIENT_SECRET}
      - LATIGO_TIME_SERIES_RESOURCE=${LATIGO_TIME_SERIES_RESOURCE}
      - LATIGO_TIME_SERIES_TENANT=${LATIGO_TIME_SERIES_TENANT}
      - LATIGO_TIME_SERIES_BASE_URL=${LATIGO_TIME_SERIES_BASE_URL}
      - LATIGO_TIME_SERIES_AUTH_HOST_URL=${LATIGO_TIME_SERIES_AUTH_HOST_URL}
      - LATIGO_TIME_SERIES_CLIENT_ID=${LATIGO_TIME_SERIES_CLIENT_ID}
      - LATIGO_TIME_SERIES_CLIENT_SECRET=${LATIGO_TIME_SERIES_CLIENT_SECRET}

# Second executor for executing tasks from scheduler
  latigo-executor-2:
    image: latigo-executor
    restart: always
    container_name: latigo-executor-2
    build:
      context: .
      dockerfile: Dockerfile.executor
    environment:
      - LATIGO_INSTANCE_NAME="latigo-executor-2"
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - LATIGO_EXECUTOR_CONFIG_FILE=${LATIGO_EXECUTOR_CONFIG_FILE}
      - LATIGO_GORDO_CONNECTION_STRING=${LATIGO_GORDO_CONNECTION_STRING}
      - LATIGO_GORDO_RESOURCE=${LATIGO_GORDO_RESOURCE}
      - LATIGO_GORDO_TENANT=${LATIGO_GORDO_TENANT}
      - LATIGO_GORDO_AUTH_HOST_URL=${LATIGO_GORDO_AUTH_HOST_URL}
      - LATIGO_GORDO_CLIENT_ID=${LATIGO_GORDO_CLIENT_ID}
      - LATIGO_GORDO_CLIENT_SECRET=${LATIGO_GORDO_CLIENT_SECRET}
      - LATIGO_TIME_SERIES_RESOURCE=${LATIGO_TIME_SERIES_RESOURCE}
      - LATIGO_TIME_SERIES_TENANT=${LATIGO_TIME_SERIES_TENANT}
      - LATIGO_TIME_SERIES_BASE_URL=${LATIGO_TIME_SERIES_BASE_URL}
      - LATIGO_TIME_SERIES_AUTH_HOST_URL=${LATIGO_TIME_SERIES_AUTH_HOST_URL}
      - LATIGO_TIME_SERIES_CLIENT_ID=${LATIGO_TIME_SERIES_CLIENT_ID}
      - LATIGO_TIME_SERIES_CLIENT_SECRET=${LATIGO_TIME_SERIES_CLIENT_SECRET}

# Time series database to keep sensor and prediction data (only for local dev/test)
#  influxdb:
#    image: influxdb:latest
#    restart: always
#    container_name: influxdb

#    ports:
#      - "8083:8083"
#      - "8086:8086"
#      - "8090:8090"
#    environment:
#     - INFLUXDB_DB=${INFLUXDB_DB}
#     - INFLUXDB_ADMIN_ENABLED=${INFLUXDB_ADMIN_ENABLED}
#     - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
#     - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
#     - INFLUXDB_USER=${INFLUXDB_USER}
#     - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
#    volumes:
#      # sudo mkdir -p ../volumes/latigo/influxdb/data
#      - ../volumes/latigo/influxdb:/var/lib/influxdb

# Visualization tool for influx and postgres
#  grafana:
#    image: grafana/grafana:latest
#    restart: always
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    environment:
#     - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
#    links:
#      - influxdb
#      - postgres
#    volumes:
#      # sudo mkdir -p ../volumes/latigo/grafana/data
#      # sudo chown 472:472 ../volumes/latigo/grafana/data
#      - ../volumes/latigo/grafana:/var/lib/grafana
