version: '3.4'

services:

# Scheduler that produces tasks for executors
  latigo-scheduler:
    image: latigo-scheduler
    restart: always
    container_name: latigo-scheduler
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    links:
      - postgres
    volumes:
      - ../volumes/latigo/scheduler:/tmp/data:Z
    environment:
      - LATIGO_INSTANCE_NAME="latigo-scheduler"
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - LATIGO_INTERNAL_DATABASE=${LATIGO_INTERNAL_DATABASE}
      - LATIGO_SCHEDULER_CONFIG_FILE=${LATIGO_SCHEDULER_CONFIG_FILE}
      - LATIGO_GORDO_RESOURCE=${LATIGO_GORDO_RESOURCE}
      - LATIGO_GORDO_TENANT=${LATIGO_GORDO_TENANT}
      - LATIGO_GORDO_AUTH_HOST_URL=${LATIGO_GORDO_AUTH_HOST_URL}
      - LATIGO_GORDO_CLIENT_ID=${LATIGO_GORDO_CLIENT_ID}
      - LATIGO_GORDO_CLIENT_SECRET=${LATIGO_GORDO_CLIENT_SECRET}

# First executor for executing tasks from scheduler
  latigo-executor-1:
    image: latigo-executor
    restart: always
    container_name: latigo-executor-1
    build:
      context: .
      dockerfile: Dockerfile.executor
    links:
      - postgres
    environment:
      - LATIGO_INSTANCE_NAME="latigo-executor-1"
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - LATIGO_INTERNAL_DATABASE=${LATIGO_INTERNAL_DATABASE}
      - LATIGO_EXECUTOR_CONFIG_FILE=${LATIGO_EXECUTOR_CONFIG_FILE}
      - LATIGO_GORDO_RESOURCE=${LATIGO_GORDO_RESOURCE}
      - LATIGO_GORDO_TENANT=${LATIGO_GORDO_TENANT}
      - LATIGO_GORDO_AUTH_HOST_URL=${LATIGO_GORDO_AUTH_HOST_URL}
      - LATIGO_GORDO_CLIENT_ID=${LATIGO_GORDO_CLIENT_ID}
      - LATIGO_GORDO_CLIENT_SECRET=${LATIGO_GORDO_CLIENT_SECRET}
      - LATIGO_TIME_SERIES_RESOURCE=${LATIGO_TIME_SERIES_RESOURCE}
      - LATIGO_TIME_SERIES_TENANT=${LATIGO_TIME_SERIES_TENANT}
      - LATIGO_TIME_SERIES_BASE_URL=${LATIGO_TIME_SERIES_BASE_URL}
      - LATIGO_TIME_SERIES_AUTH_HOST_URL=${LATIGO_TIME_SERIES_AUTH_HOST_URL}
      - LATIGO_TIME_SERIES_CLIENT_ID=${LATIGO_TIME_SERIES_CLIENT_ID}
      - LATIGO_TIME_SERIES_CLIENT_SECRET=${LATIGO_TIME_SERIES_CLIENT_SECRET}

# Second executor for executing tasks from scheduler
  latigo-executor-2:
    image: latigo-executor
    restart: always
    container_name: latigo-executor-2
    build:
      context: .
      dockerfile: Dockerfile.executor
    links:
      - postgres
    environment:
      - LATIGO_INSTANCE_NAME="latigo-executor-2"
      - LATIGO_INTERNAL_EVENT_HUB=${LATIGO_INTERNAL_EVENT_HUB}
      - LATIGO_INTERNAL_DATABASE=${LATIGO_INTERNAL_DATABASE}
      - LATIGO_EXECUTOR_CONFIG_FILE=${LATIGO_EXECUTOR_CONFIG_FILE}
      - LATIGO_GORDO_RESOURCE=${LATIGO_GORDO_RESOURCE}
      - LATIGO_GORDO_TENANT=${LATIGO_GORDO_TENANT}
      - LATIGO_GORDO_AUTH_HOST_URL=${LATIGO_GORDO_AUTH_HOST_URL}
      - LATIGO_GORDO_CLIENT_ID=${LATIGO_GORDO_CLIENT_ID}
      - LATIGO_GORDO_CLIENT_SECRET=${LATIGO_GORDO_CLIENT_SECRET}
      - LATIGO_TIME_SERIES_RESOURCE=${LATIGO_TIME_SERIES_RESOURCE}
      - LATIGO_TIME_SERIES_TENANT=${LATIGO_TIME_SERIES_TENANT}
      - LATIGO_TIME_SERIES_BASE_URL=${LATIGO_TIME_SERIES_BASE_URL}
      - LATIGO_TIME_SERIES_AUTH_HOST_URL=${LATIGO_TIME_SERIES_AUTH_HOST_URL}
      - LATIGO_TIME_SERIES_CLIENT_ID=${LATIGO_TIME_SERIES_CLIENT_ID}
      - LATIGO_TIME_SERIES_CLIENT_SECRET=${LATIGO_TIME_SERIES_CLIENT_SECRET}

# Relational db for maintaining some state
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
     - ../volumes/latigo/postgres:/var/lib/postgresql/data:Z

# Tool for easily managing relational database in browser
#  adminer:
#    image: adminer
#    restart: always
#    container_name: adminer
#    ports:
#      - 8080:8080


# Time series database to keep sensor and prediction data
  influxdb:
    image: influxdb:latest
    restart: always
    container_name: influxdb

    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
     - INFLUXDB_DB=${INFLUXDB_DB}
     - INFLUXDB_ADMIN_ENABLED=${INFLUXDB_ADMIN_ENABLED}
     - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
     - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
     - INFLUXDB_USER=${INFLUXDB_USER}
     - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    volumes:
      # sudo mkdir -p ../volumes/latigo/influxdb/data
      - ../volumes/latigo/influxdb:/var/lib/influxdb

# Visualization tool for influx and postgres
#  grafana:
#    image: grafana/grafana:latest
#    restart: always
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    environment:
#     - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
#    links:
#      - influxdb
#      - postgres
#    volumes:
#      # sudo mkdir -p ../volumes/latigo/grafana/data
#      # sudo chown 472:472 ../volumes/latigo/grafana/data
#      - ../volumes/latigo/grafana:/var/lib/grafana
