db:
    connection_string: "DO NOT PUT SECRETS IN THIS FILE"

task_queue_old:
    type: "event_hub"
    connection_string: "DO NOT PUT SECRETS IN THIS FILE"
    name: "executor_task_queue"
    do_trace: True
    offset_persistence:
        type: "memory"
        name: "arnold"

task_queue:
    type: "kafka"
    connection_string: "DO NOT PUT SECRETS IN THIS FILE"
    security.protocol: "SASL_SSL"
    ssl.ca.location: "/etc/ssl/certs/ca-certificates.crt"
    sasl.mechanism: "PLAIN"
    group.id: "1"
    client.id: "executor"
    request.timeout.ms: 10000
    session.timeout.ms: 10000
    default.topic.config: {"auto.offset.reset": "smallest"}
    debug: "fetch"
    topic: "latigo_topic"
    enable.auto.commit: true
    auto.commit.interval.ms: 1000

sensor_data:
    type: "timeseries_api"
    connection_string: "DO NOT PUT SECRETS IN THIS FILE"
    partition: "0"
    do_trace: False
    n_retries: 5

prediction_storage:
    type: "timeseries_api"
    connection_string: "DO NOT PUT SECRETS IN THIS FILE"
    partition: "0"
    do_trace: False
    n_retries: 5

predictor:
    type: "gordo"
    connection_string: "https://gordotest28.omnia-aurora-equinor.net/gordo/v0/"
    projects: ['ioc-1130']
    target: null
    metadata: null
    batch_size: 1000
    parallelism: 10
    forward_resampled_sensors : false
    ignore_unhealthy_targets: true
    n_retries: 5
    data_provider:
        debug: true
        n_retries: 5
    prediction_forwarder:
        debug: false
        n_retries: 5
    auth:
        resource: "set from env"
        tenant: "set from env"
        authority_host_url: "set from env"
        client_id: "set from env"
        client_secret: "DO NOT PUT SECRETS IN THIS FILE"
