executor:
    instance_count: 1
    restart_interval_sec: 21600

task_queue:
    type: "kafka"
    connection_string: "DO NOT PUT SECRETS IN THIS FILE"
    poll_timeout_sec: 100000
    security.protocol: "SASL_SSL"
    ssl.ca.location: "/etc/ssl/certs/ca-certificates.crt"
    sasl.mechanism: "PLAIN"
    group.id: "1"
    client.id: "executor"
    request.timeout.ms: 10000
    session.timeout.ms: 10000
    default.topic.config: {"auto.offset.reset": "smallest"}
    debug: "fetch"
    topic: "latigo_topic"
    enable.auto.commit: true
    auto.commit.interval.ms: 1000
    max.poll.interval.ms: 86400000

model_info:
    type: "gordo"
    connection_string: "DO NOT PUT SECRETS IN THIS FILE"
    target: null
    metadata: null
    batch_size: 1000
    parallelism: 10
    forward_resampled_sensors : false
    ignore_unhealthy_targets: true
    n_retries: 5
    data_provider:
        debug: true
        n_retries: 5
    prediction_forwarder:
        debug: false
        n_retries: 5
    auth:
        resource: "set from env"
        tenant: "set from env"
        authority_host_url: "set from env"
        client_id: "set from env"
        client_secret: "DO NOT PUT SECRETS IN THIS FILE"

sensor_data:
    type: "time_series_api"
    base_url: "https://api.gateway.equinor.com/plant-beta/timeseries/v1.5"
    async: False
    auth:
        resource: "not set from env in executor_config.yaml"
        tenant: "not set from env in executor_config.yaml"
        authority_host_url: "not set from env in executor_config.yaml"
        client_id: "not set from env in executor_config.yaml"
        client_secret: "DO NOT PUT SECRETS IN THIS FILE"
        scope: ['read', 'write']

prediction_storage:
    type: "time_series_api"
    base_url: "https://api.gateway.equinor.com/plant-beta/timeseries/v1.5"
    async: False
    auth:
        resource: "not set from env in executor_config.yaml"
        tenant: "not set from env in executor_config.yaml"
        authority_host_url: "not set from env in executor_config.yaml"
        client_id: "not set from env in executor_config.yaml"
        client_secret: "DO NOT PUT SECRETS IN THIS FILE"
        scope: ['read', 'write']

predictor:
    type: "gordo"
    connection_string: "DO NOT PUT SECRETS IN THIS FILE"
    target: null
    metadata: null
    batch_size: 1000
    parallelism: 10
    forward_resampled_sensors : false
    ignore_unhealthy_targets: true
    n_retries: 5
    use_parquet: true
    data_provider:
        debug: true
        n_retries: 5
    prediction_forwarder:
        debug: false
        n_retries: 5
    auth:
        resource: "not set from env in executor_config.yaml"
        tenant: "not set from env in executor_config.yaml"
        authority_host_url: "not set from env in executor_config.yaml"
        client_id: "not set from env in executor_config.yaml"
        client_secret: "DO NOT PUT SECRETS IN THIS FILE"
