task_queue:
    type: "kafka"
    connection_string: "DO NOT PUT SECRETS IN THIS FILE"
    security.protocol: "SASL_SSL"
    ssl.ca.location: "/etc/ssl/certs/ca-certificates.crt"
    sasl.mechanism: "PLAIN"
    group.id: "1"
    client.id: "latigo_scheduler"
    request.timeout.ms: 10000
    session.timeout.ms: 10000
    default.topic.config: {"auto.offset.reset": "smallest"}
    debug: "fetch"
    topic: "latigo_topic"
    enable.auto.commit: true
    auto.commit.interval.ms: 1000


scheduler:
    continuous_prediction_start_time: "08:00"
    continuous_prediction_interval: "90m"
    continuous_prediction_delay: "1d"
    projects: ['lat-lit']
    back_fill_max_interval: "1d"
    do_async: false


model_info:
    type: "gordo"
    connection_string: "DO NOT PUT SECRETS IN THIS FILE"
    target: null
    metadata: null
    batch_size: 1000
    parallelism: 10
    forward_resampled_sensors : false
    ignore_unhealthy_targets: true
    n_retries: 5
    data_provider:
        debug: true
        n_retries: 5
    prediction_forwarder:
        debug: false
        n_retries: 5
    auth:
        resource: "set from env"
        tenant: "set from env"
        authority_host_url: "set from env"
        client_id: "set from env"
        client_secret: "DO NOT PUT SECRETS IN THIS FILE"
