name: Latigo CI

on:
  push:
    branches:
      - master
      - stage
  pull_request:
    branches:
      - master
      - stage

env:
  DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY}}
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_REPO: ${{secrets.DOCKER_REPO}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: List environment info
      run: |
        make show-env
        make info
    - name: Build scheduler image
      run: |
        make build-scheduler
    - name: Build executor image
      run: |
        make build-executor
    - name: Push scheduler image
      run: |
        make push-scheduler
